apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
 containers:
 - name: mypod
   image: redis
   ports:
   - containerPort: 80
   volumeMounts :
   - name: sample
     mountPath: /home/labsuser/configfiles/
     readOnly: true
 volumes :
 - name: sample
   configMap:
    name: game-demo